micronaut:
  application:
    name: micronaut-crud

datasources:
  default:
    url: jdbc:tc:mysql:8.0.32:///testdb  # Testcontainers JDBC URL
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dialect: MYSQL
    schema-generate: NONE
    db-type: mysql
    migration:
      enabled: true

flyway:
  datasources:
    default:
      enabled: true
      # Use the same URL as the datasource
      url: jdbc:tc:mysql:8.0.32:///testdb
      user: root
      password: root
      locations: classpath:db/migration  # Location for your Flyway migration scripts
