micronaut:
  application:
    name: micronaut-crud

datasources:
  default:
    url: ${MYSQL_URL}  # This will be substituted with the environment variable
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}  # This will be substituted with the environment variable
    password: ${MYSQL_PASSWORD}  # This will be substituted with the environment variable
    dialect: MYSQL
    driver: com.mysql.cj.jdbc.Driver
    schema-generate: NONE
    db-type: mysql
    migration:
      enabled: true

flyway:
  datasources:
    default:
      enabled: true
      url: ${MYSQL_URL}
      user: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      locations: classpath:db/migration
